
name: capstone-final-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train & Register Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python src/train.py

      - name: Upload artifacts (logs & model)
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            logs/experiments.csv
            models/*.joblib
            data/train.csv
            data/test.csv

      - name: Deploy to HF Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python hosting/push_to_hf_space.py --space-id Gaurav328/telemetry-predict-maintenance-demo
